name: Stage the app

on:
  pull_request:
    types: [labeled]
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubunto-latest
    if: contains(github.event.pull_request.labels.*.name, 'stage')

